import pandas as pd

df= pd.read_csv(".\insurance.csv")
df.describe()
print(df.head())        
print(df.describe())
print(df.info())
print(df.tail())
print(df.columns)
print(df.shape)
print(df['age'].unique())
print(df['smoker'].value_counts())
print(df.groupby('region')['expenses'].mean())
print(df.isnull().sum())
# print(df.corr())
print(df.sort_values(by='expenses', ascending=False).head())
print(df[df['smoker']=='yes'].head())
print(df[['age', 'bmi', 'expenses']].head())
print(df[df['age'] > 50].head())       
print(df[(df['age'] > 50) & (df['smoker'] == 'yes')].head())
print(df['bmi'].mean())
print(df['bmi'].median())
print(df['bmi'].mode()) 
print(df['expenses'].min())
print(df['expenses'].max())
print(df['expenses'].std())
print(df['expenses'].var())
print(df['age'].quantile(0.25))
print(df['age'].quantile(0.75))
print(df['age'].quantile(0.5))
print(df['region'].value_counts(normalize=True))
print(df.pivot_table(values='expenses', index='smoker', columns='region', aggfunc='mean'))
print(df.sample(5)) 